# GitHub Actions workflow for scheduled runs
name: Policy Watcher Scheduler

on:
  schedule:
    - cron: '0 */8 * * *' # Every 8 hours
  workflow_dispatch:

jobs:
  run-policy-watcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run fetch.py
        run: python fetch.py
      - name: Run diff_and_notify.py
        run: python diff_and_notify.py
      - name: Trigger error handling (if needed)
        run: python create_github_issue.py
